USE [master]
GO
/****** Object:  Practica1 [bruceag]    Script Date: 19/02/2018 09:28:57 p. m. ******/
DROP DATABASE [bruceag]
GO
/****** Object:  Practica1 [bruceag]    Script Date: 19/02/2018 09:28:57 p. m. ******/
CREATE DATABASE [bruceag]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bruceag', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\bruceag.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\bruceag_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [bruceag] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bruceag].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [bruceag] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [bruceag] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [bruceag] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [bruceag] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [bruceag] SET ARITHABORT OFF 
GO
ALTER DATABASE [bruceag] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [bruceag] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [bruceag] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [bruceag] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [bruceag] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [bruceag] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [bruceag] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [bruceag] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [bruceag] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [bruceag] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [bruceag] SET  DISABLE_BROKER 
GO
ALTER DATABASE [bruceag] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [bruceag] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [bruceag] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [bruceag] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [bruceag] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [bruceag] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [bruceag] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [bruceag] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [bruceag] SET  MULTI_USER 
GO
ALTER DATABASE [bruceag] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [bruceag] SET DB_CHAINING OFF 
GO
ALTER DATABASE [bruceag] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [bruceag] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [bruceag] SET  READ_WRITE 
GO